sudo: required
services:
  - docker  #run docker first

before_install:
  - docker build -t kulbhushansaxena/react-test -f ./client/Dockerfile.dev ./client     #build the image

script:
  - docker run -e CI=true kulbhushansaxena/react-test npm run test -- --coverage   #Scripts which travs checks is sccessfull or not

after_success:
  - docker build -t kulbhushansaxena/multi-client ./client
  - docker build -t kulbhushansaxena/multi-nginx ./nginx
  - docker build -t kulbhushansaxena/multi-server ./server
  - docker build -t kulbhushansaxena/multi-worker ./worker

  #Login to docker CLI to save our images to docker hub directly
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push all images to docker hub
  - docker push kulbhushansaxena/multi-client
  - docker push kulbhushansaxena/multi-nginx
  - docker push kulbhushansaxena/multi-server
  - docker push kulbhushansaxena/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-southeast-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-2-581695759997
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY